spring:
  cloud:
    services:
      registrationMethod: route
  zipkin:
    baseUrl: https://zipkin-castellatus-wavelet.apps.pcf-gcp.alexguedes.com
  rabbitmq:
    addresses: ${vcap.services.zipkinRabbit.credentials.uri}
eureka:
  instance:
     nonSecurePort: 80
