spring:
  cloud:
    services:
      registrationMethod: route
  zipkin:
    baseUrl: http://zipkin-diphthongous-unchasteness.cfapps-03.haas-40.pez.pivotal.io/
  rabbitmq:
    addresses: ${vcap.services.zipkinRabbit.credentials.uri}
eureka:
  instance:
     nonSecurePort: 80
