spring:
  cloud:
    services:
      registrationMethod: route
eureka:
  instance:
     nonSecurePort: 80
spring:
  zipkin:
    baseUrl: http://zipkin-diphthongous-unchasteness.cfapps-03.haas-40.pez.pivotal.io/
